group = "in.openstair.background_on_back"
version = "1.0-SNAPSHOT"

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:9.3.0")
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'in.openstair.background_on_back'

    compileSdk 37

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk = 24
    }
}

dependencies {
    testImplementation("org.mockito:mockito-core:5.0.0")
}